---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "node-feature-discovery.fullname" . }}-master
  labels:
{{ include "node-feature-discovery.labels" . | indent 4 }}
spec:
  selector:
    app: {{ template "node-feature-discovery.fullname" . }}-master
  ports:
  - protocol: TCP
    port: 8080
  type: ClusterIP
