---
- name : install dependencies
  include_role:
    name: install-dependencies

- name: clone NFD repository
  git:
    repo: "{{ nfd_git_url }}"
    dest: "{{ nfd_dir }}"
    version: "{{ nfd_git_ref }}"
    force: yes
  when:
    - inventory_hostname == groups['kube-node'][0]
    - nfd_build_image_locally

- name: set proxy in Dockerfile
  lineinfile:
    path: "{{ nfd_dir }}/Dockerfile"
    regexp: "^ENV {{ item.key }}"
    line: "ENV {{ item.key }} {{ item.value }}"
    insertafter: '^FROM'
    state: present
    firstmatch: yes
  with_dict: "{{ proxy_env }}"
  when:
    - inventory_hostname == groups['kube-node'][0]
    - nfd_build_image_locally
    - '"http_proxy" in proxy_env or "https_proxy" in proxy_env'

- name: build NFD image
  make:
    target: all
    chdir: "{{ nfd_dir }}"
  when:
    - inventory_hostname == groups['kube-node'][0]
    - nfd_build_image_locally

- name: read current NFD version
  command: git describe --tags --dirty --always
  args:
    chdir: "{{ nfd_dir }}"
  register: nfd_img_version
  when:
    - inventory_hostname == groups['kube-node'][0]
    - nfd_build_image_locally

- name: tag NFD image
  command: docker tag quay.io/kubernetes_incubator/node-feature-discovery:{{ nfd_img_version.stdout }} {{ registry_local_address }}/node-feature-discovery:{{ nfd_img_version.stdout }}
  when:
    - inventory_hostname == groups['kube-node'][0]
    - nfd_build_image_locally

- name: push NFD image to local registry
  command: docker push {{ registry_local_address }}/node-feature-discovery:{{ nfd_img_version.stdout }}
  when:
    - inventory_hostname == groups['kube-node'][0]
    - nfd_build_image_locally

- name: create Helm charts directory if needed
  file:
    path: /usr/src/charts
    state: directory
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: copy NFD Helm chart to the master node
  copy:
    src: "{{ role_path }}/charts/node-feature-discovery"
    dest: "/usr/src/charts/"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: set values for NFD Helm chart values for locally built and stored image
  set_fact:
    nfd_image: "{{ registry_local_address }}/node-feature-discovery"
    nfd_version: "{{ hostvars[groups['kube-node'][0]].nfd_img_version.stdout }}"
  when:
    - nfd_build_image_locally
    - inventory_hostname == groups['kube-master'][0]

- name: populate NFD Helm chart values template and push to master node
  template:
    src: "helm_values.yml.j2"
    dest: "/usr/src/charts/nfd-values.yml"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: install NFD helm chart
  command: helm upgrade --install nfd -f /usr/src/charts/nfd-values.yml /usr/src/charts/node-feature-discovery
  when:
    - inventory_hostname == groups['kube-master'][0]
