---
{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "node-feature-discovery.fullname" . }}-worker-config
  labels:
{{ include "node-feature-discovery.labels" . | indent 4 }}
data:
  nfd-worker.conf: |
{{ toYaml .Values.config | indent 4 }}
{{- end }}