{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "node-feature-discovery.saName" . }}
  labels:
{{ include "node-feature-discovery.labels" . | indent 4 }}
{{- end }}
---
{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "node-feature-discovery.fullname" . }}
  labels:
{{ include "node-feature-discovery.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
# when using command line flag --resource-labels to create extended resources
# "- nodes/status" is needed
{{- if .Values.sgx_dp_nfd_labels }}
  - nodes/status
{{- end }}
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "node-feature-discovery.fullname" . }}
  labels:
{{ include "node-feature-discovery.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "node-feature-discovery.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "node-feature-discovery.saName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
