---
image:   
   repository: intel-qat-plugin
   tag: devel  
pullPolicy: IfNotPresent 

drivers:
  dpdk: "vfio-pci"
  kernel: "dh895xccvf,c6xxvf,c3xxxvf,d15xxvf"

maxNumDevices: "32"

debug: "false"
