##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: reset and remove Kubernetes cluster
  import_tasks: k8s_cleanup.yml

- name: remove Intel Container Experience Kit features artifacts
  import_tasks: intel_cleanup.yml

- name: reboot
  debug:
    msg: rebooting after pre-redeploy cleanup
  changed_when: true
  notify:
    - reboot server
  when: reboot_after_cleanup | default(true)
