##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: uninstall elasticsearch
  include_role:
    name: elasticsearch_install
    tasks_from: cleanup
  tags:
    - elasticsearch

- name: uninstall opentelemetry
  include_role:
    name: opentelemetry_install
    tasks_from: cleanup
  tags:
    - opentelemetry

- name: uninstall cAdvisor
  include_role:
    name: cadvisor_install
    tasks_from: cleanup_cadvisor
  tags:
    - cadvisor

- name: uninstall LinkerD
  include_role:
    name: linkerd_service_mesh
    tasks_from: uninstall
  tags:
    - linkerd_service_mesh

- name: cleanup cpu_ctlplane
  include_role:
    name: intel_cpu_controlplane
    tasks_from: cleanup_cpu_controlplane
  tags:
    - cpu_ctlplane

- name: reset and remove Kubernetes cluster
  import_tasks: k8s_cleanup.yml

- name: remove Intel Container Experience Kit features artifacts
  import_tasks: intel_cleanup.yml

- name: uninstall MinIO
  include_role:
    name: minio_install
    tasks_from: cleanup_minio_main
  tags:
    - minio

- name: reboot
  debug:
    msg: rebooting after pre-redeploy cleanup
  changed_when: true
  notify:
    - reboot server
  when: reboot_after_cleanup | default(true)
