##
##   Copyright (c) 2020-2023 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- name: check cAdvisor Helm charts directory
  stat:
    path: "{{ (project_root_dir, 'charts', 'cadvisor') | path_join }}"
  register: cadvisor_dir

- name: create cAdvisor Helm charts directory if needed
  file:
    path: "{{ (project_root_dir, 'charts', 'cadvisor') | path_join }}"
    state: directory
    mode: 0755
  when:
    - cadvisor_dir.stat.exists is defined and not cadvisor_dir.stat.exists

- name: check cAdvisor Helm charts temp directory.
  stat:
    path: "{{ (project_root_dir, 'charts', 'cadvisor', 'temp') | path_join }}"
  register: cadvisor_temp_dir

- name: create the temp folder for cAdvisor custom values
  file:
    path: "{{ (project_root_dir, 'charts', 'cadvisor', 'temp') | path_join }}"
    state: directory
    mode: 0755
  when:
    - cadvisor_temp_dir.stat.exists is defined and not cadvisor_temp_dir.stat.exists

- name: copy {{ perf_events_config_filename }}
  copy:
    src: "{{ (role_path, 'files', perf_events_config_filename) | path_join }}"
    dest: "{{ (project_root_dir, 'charts', 'cadvisor', 'temp') | path_join }}"
    mode: preserve

- name: populate cAdvisor Helm charts values template and push to controller node
  template:
    src: "cadvisor_custom_values.yml.j2"
    dest: "{{ (project_root_dir, 'charts', 'cadvisor', 'temp', 'cadvisor-custom-values.yml') | path_join }}"
    force: yes
    mode: preserve

- name: Add "{{ cadvisor_application_name }}" Helm Chart Repository
  command: >-
    helm repo add "{{ cadvisor_helm_chart_repo_name }}" "{{ cadvisor_helm_repo_url }}"
  changed_when: true

- name: Deploy {{ cadvisor_helm_charts_version }} of {{ cadvisor_application_name }}
  command: >-
    helm install
    {{ cadvisor_release_name }}
    {{ cadvisor_helm_charts_ref }}
    --version={{ cadvisor_helm_charts_version }}
    --namespace {{ cadvisor_helm_release_namespace }}
    --create-namespace
    -f {{ (project_root_dir, 'charts', 'cadvisor', 'temp', 'cadvisor-custom-values.yml') | path_join }}
  changed_when: true
