---
# installs all Intel BMRA features

# note: start with the sriov-nic-init on the kube-node servers,
# so that the NIC is ready before the SRIOV Net DP is deployed cluster-wide
- hosts: kube-node
  tasks: []
  roles:
    - role: sriov-nic-init
      when: sriov_enabled | default(false) and install_dpdk | default(false)
  environment: "{{ proxy_env | d({}) }}"

- hosts: k8s-cluster
  tasks: []
  roles:
    - role: cluster-defaults
      tags: defaults
    - role: golang-install
      tags: golang
    - role: multus-cni-install
      when: (inventory_hostname == groups['kube-master'][0]) and (force_external_multus_installation | default(false))
      tags: multus
    - role: net-attach-defs-create
      tags: net-attach-defs
      when: inventory_hostname == groups['kube-master'][0]
    - role: nfd-install
      tags: nfd
      when: nfd_enabled | default(true)
    - role: sriov-dp-install
      tags: sriov-net-dp
      when: sriov_net_dp_enabled | default(true)
    - role: intel-device-plugins-install
      when: (qat_dp_enabled | default(true)) or (gpu_dp_enabled | default(true))
      tags: intel-device-plugins
    - role: cmk-install
      tags: cmk
      when: cmk_enabled | default(true)
    - role: tas-install
      tags: tas-install
      when: tas_enabled | default(true)
  environment: "{{ proxy_env | d({}) }}"

- hosts: kube-node
  tasks: []
  roles:
    - role: cluster-defaults
      tags: defaults
    - role: dpdk-install
      when: ovs_dpdk_enabled or install_dpdk | default(false)
      tags: dpdk
    - role: sriov-cni-install
      when: sriov_cni_enabled | default(true)
      tags: sriov-cni
    - role: bond-cni-install
      when: bond_cni_enabled | default(true)
      tags: bond-cni
    # install Go 1.11.9 required by userspace-cni
    - role: golang-install
      tags: userspace-cni
      when: userspace_cni_enabled | default(true)
      vars:
        golang_version: 1.11.9
    - role: userspace-cni-install
      when: userspace_cni_enabled | default(true)
      tags: userspace-cni
  environment: "{{ proxy_env | d({}) }}"
