##
##   Copyright (c) 2020-2022 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
docker_version: stable
docker_cli_version: "{{ docker_version }}"

# A string of extra options to pass to the docker daemon.
# This string should be exactly as you wish it to appear.
# docker_options: ""

# define docker bin_dir
docker_bin_dir: "/usr/bin"

# Used to set docker daemon iptables options to true
docker_iptables_enabled: true

docker_registry_mirrors: []
docker_insecure_registries: []

# Docker Cgroup driver (native.cgroupdriver)
# Valid options are systemd or cgroupfs
docker_cgroup_driver: systemd

# Path used to store Docker data
docker_daemon_graph: "/var/lib/docker"

# Docker log options
# Rotate container stderr/stdout logs at 50m and keep last 5
docker_log_opts: "--log-opt max-size=50m --log-opt max-file=5"

## If non-empty will override default system MountFlags value.
## This option takes a mount propagation flag: shared, slave
## or private, which control whether mounts in the file system
## namespace set up for docker will receive or propagate mounts
## and unmounts. Leave empty for system default
# docker_mount_flags:

# keep docker packages after installation; speeds up repeated ansible provisioning runs when '1'
# docker_rpm_keepcache: 1

yum_repo_dir: /etc/yum.repos.d
