apiVersion: v1
kind: ConfigMap
metadata:
  name: cni-configuration
  namespace: kube-system
data:
  cni-config: |-
    {
        "name": "chained",
        "cniVersion": "0.3.1",
        "plugins": [
            {
                "type": "cilium-cni"
            },
            {
                "type": "adq-cni",
                "tunneling": "disabled",
                "tunneling-interface": ""
            }
        ]
    }
