---
# TODO: bootstrap Ansible host in a separate role
- hosts: localhost
  tasks: []
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true

# apply common cluster node configuration
- hosts: k8s-cluster
  tasks: []
  handlers:
    - name: reboot server
      reboot: { reboot_timeout: 1200 }
  roles:
    - role: cluster-defaults
    - role: bootstrap/configure-proxy
    - role: bootstrap/install-packages
    - role: bootstrap/configure-security
    - role: bootstrap/apply-kubernetes-reqs
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true

# apply additional worker node specific configuration that may require reboot
- hosts: kube-node
  tasks: []
  handlers:
    - name: reboot server
      reboot: { reboot_timeout: 1200 }
  roles:
    - role: cluster-defaults
    - role: bootstrap/configure-hugepages
    - role: bootstrap/configure-cpu-isolation
    - role: bootstrap/set-sriov-kernel-flags
    - role: bootstrap/update-nic-drivers
    - role: bootstrap/configure-qat
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true

# install DPDK and apply SRIOV configuration, configure SST-BF
- hosts: kube-node
  roles:
    - role: cluster-defaults
    - role: install-dpdk
      when: ovs_dpdk_enabled or install_dpdk | default(false)
      tags: dpdk
    - role: install-ddp-pkgs
      when: install_ddp_packages | default(false) | bool
    - role: sriov-nic-init
      when: sriov_enabled | default(false) and install_dpdk | default(false)
    - role: sst-bf-configure
      when: sst_bf_configuration_enabled | default(true)
      tags: sst-bf
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true