- hosts: k8s-cluster
  tasks: []
  roles:
    - { role: k8s-all-preconfigure }
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true

- hosts: kube-node
  tasks: []
  roles:
    - { role: k8s-node-preconfigure }
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true
