---
- name: install dependencies on Red Hat
  yum:
    name:
      - pygpgme
      - yum-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: add fdio repo gpg key
  apt_key:
    url: "https://packagecloud.io/fdio/{{ vpp_version }}/gpgkey"
    state: present
  when: ansible_os_family == "Debian"

- name: setup vpp repo for Ubuntu
  template:
    src: 99fd.io.list
    dest: /etc/apt/sources.list.d/99fd.io.list
  when: ansible_os_family == "Debian"
  register: vpp_sh_deb

- name: setup vpp repo on Red Hat
  template:
    src: fdio.repo
    dest: /etc/yum.repos.d/fdio.repo
  when: ansible_os_family == "RedHat"
  register: vpp_sh_rh

- name: write sys config with hugepages and memory settings
  template:
    src: 80-vpp.conf.j2
    dest: /etc/sysctl.d/80-vpp.conf

- name: apply sysctl config
  command: sysctl -p --load=/etc/sysctl.d/80-vpp.conf

- name: install vpp packages on Red Hat
  yum:
    name:
      - vpp
      - vpp-plugins
      - vpp-devel
      - vpp-api-python
      - vpp-api-lua
      - vpp-api-java
    state: present
  when: ansible_os_family == "RedHat"

- name: install vpp packages on Debian
  apt:
    update_cache: yes
    name:
      - vpp
      - vpp-plugins
      - vpp-dev
      - vpp-lib
      - vpp-dbg
      - vpp-api-python
      - vpp-api-lua
      - vpp-api-java
    state: present
  when: ansible_os_family == "Debian"

# NOTE: questions:
#       do we need to update vpp config to apply some optimizations?
#       attach NIC ports based on the user configuration?
#       run vpp in the CMK context?

- name: Restart VPP service
  systemd:
    name: vpp
    state: restarted
    daemon_reload: yes
