##
##   Copyright (c) 2020 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
dpdk_url: http://fast.dpdk.org/rel/dpdk-19.11.tar.xz
dpdk_target: x86_64-native-linuxapp-gcc

install_dependencies:
  Debian:
    - build-essential
    - libnuma-dev
    - libpcap-dev
    - linux-headers-{{ ansible_kernel }}
    - python
  RedHat:
    - numactl-devel
    - libpcap-devel
    - kernel-devel
    - "@Development tools"
    - elfutils-libelf-devel
