---
- name: build Intel QAT Device Plugin image
  make:
    target: intel-qat-plugin
    chdir: "{{ intel_dp_dir }}"
  when:
    - inventory_hostname == groups['kube-node'][0]

- name: tag Intel QAT Device Plugin image
  command: docker tag intel/intel-qat-plugin:{{ intel_dp_version }} {{ registry_local_address }}/intel-qat-plugin:latest
  when:
    - inventory_hostname == groups['kube-node'][0]

- name: push Intel QAT Device Plugin image to local registry
  command: docker push {{ registry_local_address }}/intel-qat-plugin:latest
  when:
    - inventory_hostname == groups['kube-node'][0]

- name: copy Helm chart to the master node
  copy:
    src: "{{ role_path }}/charts/intel-qat-plugin"
    dest: "/usr/src/charts/"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: set values for Helm charts
  set_fact:
    qat_dp_image: "{{ registry_local_address }}/intel-qat-plugin"
    qat_dp_version: latest
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: populate Intel QAT Plugin Helm chart values template and push to master node
  template:
    src: "qat_values.yml.j2"
    dest: "/usr/src/charts/intel-qat-plugin-values.yml"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: install Intel QAT Plugin Helm chart
  command: helm upgrade -i intel-qat-plugin -f /usr/src/charts/intel-qat-plugin-values.yml --namespace {{ qat_dp_namespace }} /usr/src/charts/intel-qat-plugin
  when:
    - inventory_hostname == groups['kube-master'][0]
