apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-agent-cadvisor
  namespace: monitoring
spec:
  secretName: otel-agent-cadvisor
  dnsNames:
  - otel-gateway-collector-headless.monitoring.svc.cluster.local
  - otel-gateway-collector-headless.monitoring.svc
  - otel-gateway-collector-headless.monitoring
  - otel-gateway-collector-headless
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: elasticsearch-tls-ca-issuer
    kind: Issuer
    group: cert-manager.io
  usages:
  - client auth
  - server auth
  - digital signature
  - key encipherment
