---
- name: create Helm charts directory if needed
  file:
    path: /usr/src/charts
    state: directory
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: install prometheus node exporter helm chart 
  import_tasks: prometheus_node_exporter.yml
  when: tas_enabled

- name: install prometheus helm chart
  import_tasks: prometheus.yml
  when: tas_enabled

- name: install prometheus custom metrics helm chart
  import_tasks: prometheus_custom_metrics.yml
  when: tas_enabled

- name: install TAS
  import_tasks: tas.yml
  when: tas_enabled


