---
- name: create a namespace for Prometheus Adapter
  k8s:
    name: "{{ prometheus_custom_metrics_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  when:
    inventory_hostname == groups['kube-master'][0]

- name: populate Prometheus Adapter Helm chart values template and push to master node
  template:
    src: "prometheus-adapter-values.yml.j2"
    dest: "/usr/src/charts/prometheus-adapter-values.yml"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: populate Prometheus Adapter rbac template and push to master node
  template:
    src: "prometheus-adapter-rbac.yml.j2"
    dest: "/usr/src/charts/prometheus-adapter-rbac.yml"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: create rbac for node resource reader
  command: kubectl apply -f prometheus-adapter-rbac.yml
  args:
    chdir: /usr/src/charts
  when:
    - inventory_hostname == groups['kube-master'][0]      

- name: install Prometheus Custom Metrics Helm chart
  command: helm upgrade --install --namespace {{ prometheus_custom_metrics_namespace }} {{ prometheus_custom_metrics_name}} -f prometheus-adapter-values.yml stable/prometheus-adapter
  args:
    chdir: "/usr/src/charts/"
  when:
    inventory_hostname == groups['kube-master'][0]
