---
- name : install dependencies
  include_role:
    name: install-dependencies

- name: clone TAS repository
  git:
    repo: "{{ tas_git_url }}"
    dest: "{{ tas_dir }}"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: make build and make image - TAS 
  make:   
    target: "{{ item }}"
    chdir: "{{ tas_dir }}"
  when:
    - inventory_hostname == groups['kube-master'][0]
  loop:
    - build
    - image

- name: tag TAS-controller and TAS-extender
  command: docker tag {{ item }}:{{ tas_version }} {{ registry_local_address }}/{{ item }}:{{ tas_version }}
  when:
    - inventory_hostname == groups['kube-master'][0]
  loop:
    - tas-controller
    - tas-extender
    
- name: push TAS-controller and TAS-extender image to local registry
  command: docker push {{ registry_local_address }}/{{item}}:{{ tas_version }}
  when:
    - inventory_hostname == groups['kube-master'][0]
  loop:
    - tas-controller
    - tas-extender

- name: change file access rights
  file:
    path: "{{ extender_dir }}/configure-scheduler.sh"
    group: root
    owner: root
    mode: '0711'

- name: configure Scheduler
  command: sh configure-scheduler.sh
  args:
    chdir: "{{ extender_dir }}"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: create descheduler directory if needed
  file:
    path: "{{ sigs_k8s_io_dir }}"
    state: directory
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: clone Descheduler for Kubernetes
  git:
    repo: "{{ descheduler_git_url }}"
    dest: "{{ descheduler_dir }}"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: install descheduler
  make:
    chdir: "{{ descheduler_dir }}"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: copy Helm chart and TASPolicy resource definition to master node
  copy:
    src: "{{ role_path }}/charts/{{ item }}"
    dest: "/usr/src/charts/"
  when:
    - inventory_hostname == groups['kube-master'][0]
  loop:
    - telemetry-aware-scheduling
    - tas-policy-crd.yml

- name: populate tas Helm chart values template and push to master node
  template:
    src: "tas-values.yml.j2"
    dest: "/usr/src/charts/tas-values.yml"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: create TASPolicy resource
  command: kubectl apply -f tas-policy-crd.yml
  args:
    chdir: "/usr/src/charts"
  when:
    - inventory_hostname == groups['kube-master'][0]
  
- name: install TAS helm chart
  command: helm upgrade --install --namespace {{ tas_namespace }} {{ tas_name }} -f tas-values.yml telemetry-aware-scheduling/
  args:
    chdir: "/usr/src/charts"
  when:
    - inventory_hostname == groups['kube-master'][0]
  retries: 5
  delay: 5
  register: result
  until: result.rc == 0

- name: set demo health metric for all nodes
  copy: 
    content='node_health_metric 1'
    dest=/tmp/node-metrics/text.prom
