##
##   Copyright (c) 2020-2023 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
---
- block:
    - name: check whether service exists
      stat:
        path: '/lib/systemd/system/cek_config_dpdk.service'
      register: config_dpdk_service_status

    - name: disable that service which will do dpdk rebind after reboot
      systemd:
        name: cek_config_dpdk
        state: stopped
        enabled: false
        daemon_reload: true
      when: config_dpdk_service_status.stat.exists
      become: true

    - name: check whether unbind script exists
      stat:
        path: '/usr/local/bin/cek_config_dpdk_unbind.py'
      register: config_dpdk_unbind_script_status

    - block:
        - name: execute dpdk unbind script
          command: "python /usr/local/bin/cek_config_dpdk_unbind.py"
          register: dpdk_unbind_result
          changed_when: false

        - name: output dpdk unbind result
          debug:
            msg: "{{ dpdk_unbind_result.stdout_lines }}"
      when: config_dpdk_unbind_script_status.stat.exists

    - name: remove config dpdk scripts
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - '/usr/local/bin/cek_config_dpdk_bind.py'
        - '/usr/local/bin/cek_config_dpdk_rebind.py'
        - '/usr/local/bin/cek_config_dpdk_link.py'
        - '/usr/local/bin/cek_config_dpdk_unbind.py'
        - '/usr/local/bin/cek_config_dpdk_util.py'
        - '/usr/local/bin/cek_config_dpdk.sh'
        - '/lib/systemd/system/cek_config_dpdk.service'
      become: true
