---
sriov_net_dp_git_url: "https://github.com/intel/sriov-network-device-plugin.git"
sriov_net_dp_git_ref: "v3.0.0"
sriov_net_dp_dir: "/usr/src/sriov-network-device-plugin"
sriov_net_dp_build_image_locally: true
sriov_net_dp_autogenerate: true
sriov_net_dp_namespace: kube-system


registry_local_address: "localhost:5000"
