---
- assert:
    that:
      - "kube_network_plugin_multus == true"
    fail_msg: "Multus must be enabled to have fully functional cluster deployment"

- assert:
    that:
      - "helm_enabled == true"
    fail_msg: "Helm must be enabled to have fully functional cluster deployment"

- assert:
    that:
      - "registry_enabled == true"
    fail_msg: "Docker registry must be enabled to have fully functional cluster deployment"

- name: install kubespray python requirements
  pip:
    requirements: "{{ playbook_dir }}/kubespray/requirements.txt"
