##
##   Copyright (c) 2020-2023 Intel Corporation.
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
##
confirmed_atom_cpus:
  - "x6200FE"
  - "x6212RE"
  - "x6414RE"
  - "x6425RE"
  - "x6427FE"

confirmed_core_cpus:
  - "1115GRE"
  - "1145GRE"
  - "1185GRE"
  - "12100E"
  - "12500E"
  - "12700E"
  - "12900E"
  - "12700"
  - "12900"
  - "1360P"


confirmed_skl_cpus:
  # Sky Lake Xeon Gold (quad)
  - "6152"
  # Sky Lake Xeon Platinum (octa)
  - "8176"

confirmed_clx_ncpus:
  - "5218N"
  - "6252N"
  - "6230N"

confirmed_clx_cpus:
  - "6252"

confirmed_icx_cpus:
  - "06/6c"
  - "5318N"
  - "6338"
  - "6338N"
  - "6346"
  - "6348"
  - "8358"
  - "8360Y"
  - "8380"
  - "$0000%@"

confirmed_spr_cpus:
  - "6421N"
  - "6438N"
  - "8470N"
  - "8471N"
  - "8478C"
  - "8480"
  - "8480+"
  - "8487C"
  - "8490H"
  - "0000%@"
  - "0000"

confirmed_emr_cpus:
  - "0000"
  - "8592"
  - "6548N"
