# Default values for telemetry-aware-schedulng.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

controllerImage:
  repository: "localhost:5000/tas-controller" 
  tag: latest
  pullPolicy: IfNotPresent

extenderImage:
  repository: "localhost:5000/tas-extender"
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
namespace: default
fullnameOverride: ""

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

tls:
  enabled: false
  # secretName: extender-secret
  # key: <key>
  # certificate: <secret>

taspolicy:
  create: false
  # deschedule:
  #   enabled: true
  #   rules:
  #   - name: "health_metric"
  #     operator: "Equals"
  #     target: 2
  # dontschedule:
  #   enabled: true
  #   rules:
  #   - name: "health_metric"
  #     operator: "Equals"
  #     target: 1
  #   - name: "health_metric"
  #     operator: "Equals"
  #     target: 2
  # scheduleonmetric:
  #   enabled: true
  #   rules:
  #     name: "health_metric"
  #     operator: "LessThan"
