---
# Kubernetes node configuration

# Enable SR-IOV networking related setup
sriov_enabled: false

# sriov_nics: SR-IOV PF specific configuration list
sriov_nics:
  - name: enp24s0f0              # PF interface names
    sriov_numvfs: 2              # number of VFs to create for this PF(enp24s0f0)
    vf_driver: vfio-pci          # VF driver to be attached for all VFs under this PF(enp24s0f0), "i40evf", "iavf", "vfio-pci", "igb_uio"
    ddp_profile: "gtp.pkgo"      # DDP package name to be loaded into the NIC
  - name: enp24s0f1
    sriov_numvfs: 4
    vf_driver: iavf

sriov_cni_enabled: true

# install DPDK
install_dpdk: true # DPDK installation is required for sriov_enabled:true; default to false

userspace_cni_enabled: true
vpp_enabled: true
ovs_dpdk_enabled: true
# CPU mask for OVS-DPDK PMD threads
ovs_dpdk_lcore_mask: 0x1
# Huge memory pages allocated by OVS-DPDK per NUMA node in megabytes
# example 1: "256,512" will allocate 256MB from node 0 abd 512MB from node 1
# example 2: "1024" will allocate 1GB fron node 0 on a single socket board, e.g. in a VM
ovs_dpdk_socket_mem: "256,0"

# Set to 'true' to update i40e and i40evf kernel modules
force_nic_drivers_update: true

# install Intel x700 & x800 series NICs DDP packages
install_ddp_packages: true

# Enables hugepages support
hugepages_enabled: true

# Hugepage sizes available: 2M, 1G
default_hugepage_size: 2M

# Sets how many hugepages of each size should be created
hugepages_1G: 0
hugepages_2M: 128

# CPU isolation from Linux scheduler
isolcpus_enabled: true
isolcpus: "4-7"
